### ISSUE TITLE
2.0.0 doesn't work on device

### ISSUE THREAD

**Issue by iMaciah** [animecyc/TitaniumAnimator#15]
The module works on simulator, but doesn't build on device (or distribution), here's a copy of the error:

```
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld Build/Intermediates/Ivanlance.build/Debug-iphoneos/Ivanlance.build/Objects-normal/arm64/Ivanlance normal arm64
[ERROR] :  (1 failure)
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/Maciah/.appcelerator/install/5.0.1/package/node_modules/appc-cli-titanium/plugins/run.js:89:66)
    at ChildProcess.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
```

It seems to be related to 64bit support. (1.2.0-dev and 1.1.0 work on device, but they are really buggy)

UPDATE: After looking into the log, the problem seems to be here:

```
[TRACE]  Undefined symbols for architecture arm64:
[TRACE]    "_OBJC_CLASS_$_TiUIScrollViewProxy", referenced from:
[TRACE]        objc-class-ref in libcom.animecyc.animator.a(ComAnimecycAnimatorModule.o)
[TRACE]  ld: symbol(s) not found for architecture arm64
[TRACE]  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]  ** BUILD FAILED **
```

**Comment by iMaciah** [comment]
Just hoping @animecyc can take a look at this issue, I've tried all the "solutions" I've found on google for similar issues, so far all of them have failed. It's a great module, I would love to use it for my app.

**Comment by McDo** [comment]
@iMaciah It means you should create the Ti.UI.ScrollView in advance in order to use this module. you could create a metadata.json file in your project root directory, and put the snippets below into it:
{"exports": [
"Ti.UI.createScrollView"
]}
Or you could just Ti.UI.createScrollView() in your alloy.js file.

**Comment by yozef** [comment]
Thanks @McDo thats an odd addition, but it worked.
